import {
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaPython,
  FaReact,
  FaNodeJs,
  FaGitAlt,
  FaMobileAlt,
  FaSearch,
  FaPencilRuler,
  FaLinux,
  FaWindows,
  FaNpm,
  FaYarn,
} from "react-icons/fa";
import {
  SiMongodb,
  SiFirebase,
  SiTailwindcss,
  SiJest,
  SiRedux,
  SiDjango,
  SiFlask,
  SiFastapi,
  SiPostman,
  SiNextdotjs,
  SiFigma,
  SiAdobe,
  SiMysql,
  SiVite,
  SiVisualstudiocode,
  SiDocker,
  SiJenkins,
  SiAmazonaws,
  SiNetlify,
  SiVercel,
  SiHeroku,
  SiCypress,
  SiTestinglibrary,
} from "react-icons/si";

// Updated to include icons for previously null values
export const skills = {
  theObvious: [
    { name: "HTML", icon: FaHtml5 },
    { name: "CSS", icon: FaCss3Alt },
    { name: "JavaScript", icon: FaJs },
    { name: "Python", icon: FaPython },
    { name: "MongoDB", icon: SiMongodb },
    { name: "Firebase", icon: SiFirebase },
    { name: "SQL", icon: SiMysql },
    { name: "Design Systems", icon: FaPencilRuler },
    { name: "Responsive Design", icon: FaMobileAlt },
    { name: "SEO", icon: FaSearch },
    { name: "Adobe Creative Suite", icon: SiAdobe },
    { name: "Figma", icon: SiFigma },
  ],
  librariesFrameworks: [
    { name: "React 18 & 19", icon: FaReact },
    { name: "Tailwind", icon: SiTailwindcss },
    { name: "Jest", icon: SiJest },
    { name: "Cypress", icon: SiCypress },
    { name: "React Testing Library", icon: SiTestinglibrary },
    { name: "Redux", icon: SiRedux },
    { name: "Django", icon: SiDjango },
    { name: "Flask", icon: SiFlask },
    { name: "FastAPI", icon: SiFastapi },
    { name: "Express", icon: FaNodeJs },
    { name: "NodeJS", icon: FaNodeJs },
    { name: "NextJS", icon: SiNextdotjs },
  ],
  toolsOfTheTrade: [
    { name: "Git & Version Control", icon: FaGitAlt },
    { name: "Postman", icon: SiPostman },
    { name: "npm ", icon: FaNpm, FaYarn },
    { name: "yarn", icon: FaYarn },
    { name: "Vite", icon: SiVite },
    { name: "VS Code", icon: SiVisualstudiocode },
    { name: "Linux", icon: FaLinux },
    { name: "Windows", icon: FaWindows },
    { name: "ITIL4", icon: null }, // Still no specific icon available
    { name: "Docker", icon: SiDocker },
    { name: "CI/CD", icon: SiJenkins },
    { name: "AWS", icon: SiAmazonaws },
    { name: "Netlify", icon: SiNetlify },
    { name: "Vercel", icon: SiVercel },
    { name: "Heroku", icon: SiHeroku },
  ],
};
