export const skills = {
  theObvious: [
    "HTML",
    "CSS",
    "JavaScript",
    "Python",
    "SQL",
    "Rest APIs / JSON",
    "MongoDB",
    "Firebase",
    "Design Systems",
    "Responsive Design",
    "SEO",
    "Adobe Creative Suite",
    "Figma",

    "",
  ],
  librariesFrameworks: [
    "React 18 & 19",
    "NextJS",
    "Tailwind",
    "MaterialUI",
    "ChakraUI",
    "Ant Design",
    "DaisyUI",
    "Bootstrap",
    "Cypress",
    "Jest",
    "Morgan",
    "uuidv4",
    "naniod",
    "Redux",
    "React Query",
    "React Router",
    "Axios",
    "Mongoose",
    "JwT",
    "Django",
    "Flask",
    "FastAPI",

    "express",
    "NodeJS",
  ],
  toolsOfTheTrade: [
    "Git & Version Control",
    ,
    "Jira",
    "npm / yarn",
    "Vite",
    "webpack",
    "Nx Dev",
    "VS Code",
    "Sublime Text",
    "Chrome DevTools",
    "Postman",
    "WebStorm",
    "PyCharm",
    "Artificial Intelligence",
  ],
};
